services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: networkmanager
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    ports:
      - "8082:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/networkmanager
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: password

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
